In [43]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv
/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv
/kaggle/input/datasets/binib1997/superstore/Superstore.csv
/kaggle/input/datasets/himanshunakrani/iris-dataset/iris.csv
/kaggle/input/datasets/sumanthvrao/daily-climate-time-series-data/DailyDelhiClimateTrain.csv
/kaggle/input/datasets/sumanthvrao/daily-climate-time-series-data/DailyDelhiClimateTest.csv

In [45]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# import datasets on a dataframe

In [46]:
store = pd.read_csv('/kaggle/input/datasets/binib1997/superstore/Superstore.csv', encoding='latin-1')
titanic = pd.read_csv('/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv')
iris = pd.read_csv('/kaggle/input/datasets/himanshunakrani/iris-dataset/iris.csv')
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')
climate = pd.read_csv('/kaggle/input/datasets/sumanthvrao/daily-climate-time-series-data/DailyDelhiClimateTrain.csv')

# Series

# 1. Create a series from a list

In [24]:
names= ["Sonjor", "Emon", "Anik", "Kanon"]
print("Series using List")
series= pd.Series(names)  # Create Series
print(series)

Series using List
0    Sonjor
1      Emon
2      Anik
3     Kanon
dtype: object

# 2. Create series from a dictionary

In [25]:
dictionary={          # Create Dictionary Series
    "name": "BMW X7",
    "brand": "BMW",
    "series": "3 Series",
    "price": "BDT38500000"
} 
print("Series using Dictionary")
pd.Series(dictionary)

Series using Dictionary

name           BMW X7
brand             BMW
series       3 Series
price     BDT38500000
dtype: object

# 3. Create a series from dataframe

In [26]:
SibSp= titanic["SibSp"]
pd.Series(SibSp)

0      1
1      1
2      0
3      1
4      0
      ..
886    0
887    0
888    1
889    0
890    0
Name: SibSp, Length: 891, dtype: int64

# 4. Apply below operations on a series to understand about a series

In [27]:

head= titanic.head(9)   # head operation
head
tail= titanic.tail()    # tail operation
tail
sample= titanic.sample(6)  # sample operation
sample
size= titanic.size    # size operation
size
data_type= titanic["Age"].dtype     # data type
data_type
age_index= titanic["Age"].index     # index operation
age_index
age_values= titanic["Age"].values    # values operation
age_values
titanic["Age"]= titanic["Age"].astype(np.float16)   # change data type using astype
titanic["Age"].dtype

dtype('float16')


# 5. Change data-type of a series

In [28]:
titanic["SibSp"]
print("Type if this data :", titanic["SibSp"].dtype)
print("\n Convert data type \n")
change_dtype= titanic["SibSp"].astype("float")
print("Type of this data after change data type : ",change_dtype.dtype)

Type if this data : int64

 Convert data type

Type of this data after change data type :  float64

# 6. Apply below mathematical operations on a series

In [56]:
print("Apply below mathematical operations on a series")
print("Type of this data = ", type(change_dtype))
print("\n Count = ", change_dtype.count())   # count
print("\n Sum =", change_dtype.sum())       #  sum
print("\n Products = \n", change_dtype.product)   # product
print("\n Minimum =", change_dtype.min())     # min
print("Maximum =", change_dtype.max())
print("Median =", change_dtype.median())
print("Mean =", change_dtype.mean())
print("Mod =", change_dtype.mode().values) 
print("Describe data = \n", change_dtype.describe)    # describe   
print("std = \n", change_dtype.std)      # std   
print("var = \n", change_dtype.var)     # var

Apply below mathematical operations on a series
Type of this data =  <class 'pandas.core.series.Series'>

 Count =  891

 Sum = 466.0

 Products =
 <bound method Series.prod of 0      1.0
1      1.0
2      0.0
3      1.0
4      0.0
      ...
886    0.0
887    0.0
888    1.0
889    0.0
890    0.0
Name: SibSp, Length: 891, dtype: float64>

 Minimum = 0.0
Maximum = 8.0
Median = 0.0
Mean = 0.5230078563411896
Mod = [0.]
Describe data =
 <bound method NDFrame.describe of 0      1.0
1      1.0
2      0.0
3      1.0
4      0.0
      ...
886    0.0
887    0.0
888    1.0
889    0.0
890    0.0
Name: SibSp, Length: 891, dtype: float64>
std =
 <bound method Series.std of 0      1.0
1      1.0
2      0.0
3      1.0
4      0.0
      ...
886    0.0
887    0.0
888    1.0
889    0.0
890    0.0
Name: SibSp, Length: 891, dtype: float64>
var =
 <bound method Series.var of 0      1.0
1      1.0
2      0.0
3      1.0
4      0.0
      ...
886    0.0
887    0.0
888    1.0
889    0.0
890    0.0
Name: SibSp, Length: 891, dtype: float64>

# 7. Do 3 slicing operations on a series

In [40]:

courses = pd.Series(["Python", "ML", "DL", "SQL", "AI", "Data Science"])
print("1st slicing :\n", courses[1:4])
print("2nd slicing :\n", courses[:3])
print("3rd slicing :\n",courses[3:])

1st slicing :
 1     ML
2     DL
3    SQL
dtype: object
2nd slicing :
 0    Python
1        ML
2        DL
dtype: object
3rd slicing :
 3             SQL
4              AI
5    Data Science
dtype: object

# Dataframe

# 1. Create a dataframe from a list

In [42]:
lists= [
    ["Python", "SQL", "AI", "DS"],
    [7,2,9,11]
]
print("Type of this data :", type(lists))
lists= pd.DataFrame(lists)
print("\nChange list to Dataframe :", type(lists))
print("\n",lists)

Type of this data : <class 'list'>

Change list to Dataframe : <class 'pandas.core.frame.DataFrame'>

         0    1   2   3
0  Python  SQL  AI  DS
1       7    2   9  11

# 2. Apply below dataframe understanding operations

In [31]:
# head
# tail
# sample
# info
# isnull
# duplicated

In [47]:

data = {
    "Name": ["Raju", "Karim", "Jamal", "Raju", "Nila"],
    "Age": [24, 25, 23, 24, None],
    "Course": ["CSE", "EEE", None, "CSE", "BBA"]
}

df = pd.DataFrame(data)
print("HEAD:")
print(df.head())

print("\nTAIL:")
print(df.tail())

print("\nSAMPLE:")
print(df.sample(2))

print("\nINFO:")
df.info()

print("\nISNULL:")
print(df.isnull().sum())

print("\nDUPLICATED:")
print(df.duplicated().sum())

HEAD:
    Name   Age Course
0   Raju  24.0    CSE
1  Karim  25.0    EEE
2  Jamal  23.0   None
3   Raju  24.0    CSE
4   Nila   NaN    BBA

TAIL:
    Name   Age Course
0   Raju  24.0    CSE
1  Karim  25.0    EEE
2  Jamal  23.0   None
3   Raju  24.0    CSE
4   Nila   NaN    BBA

SAMPLE:
   Name   Age Course
0  Raju  24.0    CSE
3  Raju  24.0    CSE

INFO:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     4 non-null      float64
 2   Course  4 non-null      object
dtypes: float64(1), object(2)
memory usage: 252.0+ bytes

ISNULL:
Name      0
Age       1
Course    1
dtype: int64

DUPLICATED:
1

# 2. Apply below dataframe attribute operations

In [32]:
# shape
# dtypes
# columns
# values

In [50]:

df
print("Shape:", df.shape)
print("\nData Types:")
print(df.dtypes)
print("\nColumns:")
print(df.columns)
print("\nValues:")
print(df.values)

Shape: (5, 3)

Data Types:
Name       object
Age       float64
Course     object
dtype: object

Columns:
Index(['Name', 'Age', 'Course'], dtype='object')

Values:
[['Raju' 24.0 'CSE']
 ['Karim' 25.0 'EEE']
 ['Jamal' 23.0 None]
 ['Raju' 24.0 'CSE']
 ['Nila' nan 'BBA']]

# 3. Apply below mathematical operations on a feature taken from dataframe

In [33]:
# count
# sum
# product
# min
# max
# mean
# median
# mode
# describe
# std
# var

In [57]:

age = titanic["Age"]

# Mathematical operations

print("Count:", age.count())
print("Sum:", age.sum())
print("Product:", age.prod())
print("Minimum:", age.min())
print("Maximum:", age.max())
print("Mean:", age.mean())
print("Median:", age.median())
print("Mode:", age.mode().values)
print("Standard Deviation:", age.std())
print("Variance:", age.var())

# Describe
print("\nDescribe:")
print(age.describe())

Count: 714
Sum: 21200.0
Product: inf
Minimum: 0.42
Maximum: 80.0
Mean: 29.69
Median: 28.0
Mode: [24.]
Standard Deviation: 14.52
Variance: 211.0

Describe:
count    714.000000
mean      29.687500
std       14.523438
min        0.419922
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:56: RuntimeWarning: overflow encountered in reduce
  return umr_prod(a, axis, dtype, out, keepdims, initial, where)

# Selection and filtering

In [34]:
# loc
# iloc
# isin()
# logical operation (&, |, ~)

# 1. Select 11-20th rows and total_bill and tip columns from tips dataframe

In [58]:
tips.iloc[10:20][['total_bill', 'tip']]

    total_bill   tip
10       10.27  1.71
11       35.26  5.00
12       15.42  1.57
13       18.43  3.00
14       14.83  3.02
15       21.58  3.92
16       10.33  1.67
17       16.29  3.71
18       16.97  3.50
19       20.65  3.35

# 2. Select 0-20th rows and total_bill, tip and day columns from tips dataframe

In [61]:
tips.iloc[0:21, [0,1,5]]

    total_bill   tip    time
0        16.99  1.01  Dinner
1        10.34  1.66  Dinner
2        21.01  3.50  Dinner
3        23.68  3.31  Dinner
4        24.59  3.61  Dinner
5        25.29  4.71  Dinner
6         8.77  2.00  Dinner
7        26.88  3.12  Dinner
8        15.04  1.96  Dinner
9        14.78  3.23  Dinner
10       10.27  1.71  Dinner
11       35.26  5.00  Dinner
12       15.42  1.57  Dinner
13       18.43  3.00  Dinner
14       14.83  3.02  Dinner
15       21.58  3.92  Dinner
16       10.33  1.67  Dinner
17       16.29  3.71  Dinner
18       16.97  3.50  Dinner
19       20.65  3.35  Dinner
20       17.92  4.08  Dinner

# 3. Select customers who comes in sunday and total_bill is greater than 20 dollars

In [73]:
tips.loc[ 
    (tips["day"] == "Sun") & (tips["total_bill"] > 20),
    ["total_bill", "tip", "day"]
]

     total_bill   tip  day
2         21.01  3.50  Sun
3         23.68  3.31  Sun
4         24.59  3.61  Sun
5         25.29  4.71  Sun
7         26.88  3.12  Sun
11        35.26  5.00  Sun
15        21.58  3.92  Sun
44        30.40  5.60  Sun
46        22.23  5.00  Sun
47        32.40  6.00  Sun
48        28.55  2.05  Sun
52        34.81  5.20  Sun
54        25.56  4.34  Sun
112       38.07  4.00  Sun
113       23.95  2.55  Sun
114       25.71  4.00  Sun
116       29.93  5.07  Sun
153       24.55  2.00  Sun
155       29.85  5.14  Sun
156       48.17  5.00  Sun
157       25.00  3.75  Sun
160       21.50  3.50  Sun
165       24.52  3.48  Sun
166       20.76  2.24  Sun
167       31.71  4.50  Sun
173       31.85  3.18  Sun
175       32.90  3.11  Sun
179       34.63  3.55  Sun
180       34.65  3.68  Sun
181       23.33  5.65  Sun
182       45.35  3.50  Sun
183       23.17  6.50  Sun
184       40.55  3.00  Sun
185       20.69  5.00  Sun
186       20.90  3.50  Sun
187       30.46  2.00  Sun
189       23.10  4.00  Sun

# 4. Select passengers who are male and age greater than 50 from titanic

In [79]:
titanic.loc[
    (titanic["Sex"] == "male") & (titanic["Age"] > 50),
    ["Sex", "Age"]
    ]

/usr/local/lib/python3.12/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

      Sex   Age
6    male  54.0
33   male  66.0
54   male  65.0
94   male  59.0
96   male  71.0
116  male  70.5
124  male  54.0
150  male  51.0
152  male  55.5
155  male  51.0
170  male  61.0
174  male  56.0
222  male  51.0
232  male  59.0
249  male  54.0
252  male  62.0
262  male  52.0
280  male  65.0
317  male  54.0
326  male  61.0
406  male  51.0
438  male  64.0
449  male  52.0
456  male  65.0
467  male  56.0
487  male  58.0
492  male  55.0
493  male  71.0
545  male  64.0
555  male  62.0
570  male  62.0
582  male  54.0
587  male  60.0
625  male  61.0
626  male  57.0
630  male  80.0
631  male  51.0
647  male  56.0
659  male  58.0
672  male  70.0
684  male  60.0
694  male  60.0
695  male  52.0
714  male  52.0
745  male  70.0
851  male  74.0
857  male  51.0

# 5. Select customers who are female and tip greater than 5 dollars from tips dataframe - write query operation

In [96]:
tips.query("sex == 'Female' and tip > 5")[["sex", "tip"]]

        sex   tip
52   Female  5.20
85   Female  5.17
155  Female  5.14
214  Female  6.50

# groupby

# 1. group on region based in store dataframe

In [102]:
store.groupby("Region").size()

Region
Central    2323
East       2848
South      1620
West       3203
dtype: int64

# 2. Find region-wise average sales

In [107]:
store.groupby("Region")["Sales"].mean().reset_index()

    Region       Sales
0  Central  215.772661
1     East  238.336110
2    South  241.803645
3     West  226.493233

# 3. Find region-wise average profit

In [112]:
store.groupby("Region")["Profit"].mean().reset_index()

    Region     Profit
0  Central  17.092709
1     East  32.135808
2    South  28.857673
3     West  33.849032

# 4. Find region-wise maximum profit

In [114]:
store.groupby("Region")["Profit"].max().reset_index()

    Region     Profit
0  Central  8399.9760
1     East  5039.9856
2    South  3177.4750
3     West  6719.9808

# 5. Apply multiple aggregate functions on region-wise sales

In [117]:
store.groupby("Region")["Sales"].agg(["sum", "mean", "max", "min", "median"])

                 sum        mean        max    min  median
Region
Central  501239.8908  215.772661  17499.950  0.444  45.980
East     678781.2400  238.336110  11199.968  0.852  54.900
South    391721.9050  241.803645  22638.480  1.167  54.594
West     725457.8245  226.493233  13999.960  0.990  60.840

# 6. group on region and category wise

In [119]:
store.groupby(["Region", "Category"]).size()

Region   Category
Central  Furniture           481
         Office Supplies    1422
         Technology          420
East     Furniture           601
         Office Supplies    1712
         Technology          535
South    Furniture           332
         Office Supplies     995
         Technology          293
West     Furniture           707
         Office Supplies    1897
         Technology          599
dtype: int64

# 7. Find region and category wise average sales

In [120]:
store.groupby(["Region", "Category"])["Sales"].mean()

Region   Category
Central  Furniture          340.534644
         Office Supplies    117.458801
         Technology         405.753124
East     Furniture          346.574383
         Office Supplies    120.044425
         Technology         495.278469
South    Furniture          353.309289
         Office Supplies    126.282727
         Technology         507.753952
West     Furniture          357.302325
         Office Supplies    116.422377
         Technology         420.687533
Name: Sales, dtype: float64

# 8. Find region and category wise average, minimumm, maximum and sum sales

In [130]:
store.groupby(["Region", "Category"])["Sales"].max().agg(["mean", "min", "max", "sum"]).reset_index()

  index          Sales
0  mean    9188.916667
1   min    3504.900000
2   max   22638.480000
3   sum  110267.000000

# Merging and joining

In [35]:
students = pd.DataFrame({
    "student_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
    "name": ["Rahim", "Karim", "Hasan", "Sakib", "Nabil",
             "Tanvir", "Fahim", "Rafi", "Imran", "Shakil",
             "Arif", "Jahid", "Mehedi", "Siam", "Tareq",
             "Rakib", "Adnan", "Nayeem", "Foysal", "Rony"],
    "department": ["CSE", "EEE", "CSE", "BBA", "CSE",
                   "EEE", "CSE", "BBA", "CSE", "EEE",
                   "CSE", "BBA", "EEE", "CSE", "BBA",
                   "CSE", "EEE", "CSE", "BBA", "EEE"]
})

students

    student_id    name department
0          101   Rahim        CSE
1          102   Karim        EEE
2          103   Hasan        CSE
3          104   Sakib        BBA
4          105   Nabil        CSE
5          106  Tanvir        EEE
6          107   Fahim        CSE
7          108    Rafi        BBA
8          109   Imran        CSE
9          110  Shakil        EEE
10         111    Arif        CSE
11         112   Jahid        BBA
12         113  Mehedi        EEE
13         114    Siam        CSE
14         115   Tareq        BBA
15         116   Rakib        CSE
16         117   Adnan        EEE
17         118  Nayeem        CSE
18         119  Foysal        BBA
19         120    Rony        EEE

In [36]:
results = pd.DataFrame({
    "student_id": [101, 102, 103, 105, 106, 108, 109, 111, 112, 114,
                   121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
    "math": [85, 72, 91, 68, 77, 88, 74, 95, 81, 69,
             78, 84, 92, 73, 89, 67, 80, 94, 76, 83],
    "python": [90, 75, 88, 72, 80, 92, 79, 96, 85, 71,
               82, 87, 95, 76, 91, 70, 84, 93, 78, 86]
})

results

    student_id  math  python
0          101    85      90
1          102    72      75
2          103    91      88
3          105    68      72
4          106    77      80
5          108    88      92
6          109    74      79
7          111    95      96
8          112    81      85
9          114    69      71
10         121    78      82
11         122    84      87
12         123    92      95
13         124    73      76
14         125    89      91
15         126    67      70
16         127    80      84
17         128    94      93
18         129    76      78
19         130    83      86

In [37]:
departments = pd.DataFrame({
    "dept_id": [1, 2, 3, 4],
    "department": [
        "CSE",
        "EEE",
        "BBA",
        "Civil"
    ],
    "faculty": [
        "Engineering",
        "Engineering",
        "Business",
        "Engineering"
    ]
})

departments

   dept_id department      faculty
0        1        CSE  Engineering
1        2        EEE  Engineering
2        3        BBA     Business
3        4      Civil  Engineering

# 1. Create a dataframe contains students name,faculty and number on math and python

In [156]:

df= students.merge(departments, on="department", how="left")

df= df.merge(results, on="student_id", how="inner")
df[["name", "faculty", "math", "python"]]

     name      faculty  math  python
0   Rahim  Engineering    85      90
1   Karim  Engineering    72      75
2   Hasan  Engineering    91      88
3   Nabil  Engineering    68      72
4  Tanvir  Engineering    77      80
5    Rafi     Business    88      92
6   Imran  Engineering    74      79
7    Arif  Engineering    95      96
8   Jahid     Business    81      85
9    Siam  Engineering    69      71

# 2. Department wise students count

In [158]:
students.groupby("department").size()

department
BBA    5
CSE    9
EEE    6
dtype: int64

# 3. Faculty wise department count

In [164]:
departments.groupby("faculty").count()

             dept_id  department
faculty
Business           1           1
Engineering        3           3

# 4. Find department wise highest number on each subject

In [189]:
dn = students.merge(results)

dn.groupby("department")[["math", "python"]].max()

            math  python
department
BBA           88      92
CSE           95      96
EEE           77      80

# 5. Find faculty wise highest number on each subject

In [188]:
sr= students.merge(results)
sr= sr.merge(departments)
sr.groupby("faculty")[["math", "python"]].max()

             math  python
faculty
Business       88      92
Engineering    95      96

# Time-series

In [17]:
# use climate dataset
climate

            date   meantemp    humidity  wind_speed  meanpressure
0     2013-01-01  10.000000   84.500000    0.000000   1015.666667
1     2013-01-02   7.400000   92.000000    2.980000   1017.800000
2     2013-01-03   7.166667   87.000000    4.633333   1018.666667
3     2013-01-04   8.666667   71.333333    1.233333   1017.166667
4     2013-01-05   6.000000   86.833333    3.700000   1016.500000
...          ...        ...         ...         ...           ...
1457  2016-12-28  17.217391   68.043478    3.547826   1015.565217
1458  2016-12-29  15.238095   87.857143    6.000000   1016.904762
1459  2016-12-30  14.095238   89.666667    6.266667   1017.904762
1460  2016-12-31  15.052632   87.000000    7.325000   1016.100000
1461  2017-01-01  10.000000  100.000000    0.000000   1016.000000

[1462 rows x 5 columns]

# 1. convert time into datetime

In [47]:
climate["date"]= pd.to_datetime(climate["date"])
climate["date"]

0      2013-01-01
1      2013-01-02
2      2013-01-03
3      2013-01-04
4      2013-01-05
          ...
1457   2016-12-28
1458   2016-12-29
1459   2016-12-30
1460   2016-12-31
1461   2017-01-01
Name: date, Length: 1462, dtype: datetime64[ns]

# 2. set date as index

In [48]:
climates= climate.set_index("date")
climates

             meantemp    humidity  wind_speed  meanpressure
date
2013-01-01  10.000000   84.500000    0.000000   1015.666667
2013-01-02   7.400000   92.000000    2.980000   1017.800000
2013-01-03   7.166667   87.000000    4.633333   1018.666667
2013-01-04   8.666667   71.333333    1.233333   1017.166667
2013-01-05   6.000000   86.833333    3.700000   1016.500000
...               ...         ...         ...           ...
2016-12-28  17.217391   68.043478    3.547826   1015.565217
2016-12-29  15.238095   87.857143    6.000000   1016.904762
2016-12-30  14.095238   89.666667    6.266667   1017.904762
2016-12-31  15.052632   87.000000    7.325000   1016.100000
2017-01-01  10.000000  100.000000    0.000000   1016.000000

[1462 rows x 4 columns]

# 3. Select row of 13 january, 2015

In [52]:
 climates.loc["2015-01-13"]

meantemp          12.250
humidity          77.875
wind_speed         4.875
meanpressure    1017.125
Name: 2015-01-13 00:00:00, dtype: float64

# 4. Select rows contains in april 2017

In [57]:
try:
    climates.loc['2017-04']
except KeyError as ke:
    print(f"No data found for contains April 2017 \n{ke} ")

No data found for contains April 2017
'2017-04'

# 5. Select rows from 11 september, 2014 to 25 september, 2014

In [29]:
climates.loc["2014-09-11":"2014-09-25"]

             meantemp   humidity  wind_speed  meanpressure
date
2014-09-11  26.571429  85.714286   17.825000   1005.571429
2014-09-12  28.500000  73.000000    1.625000   1005.125000
2014-09-13  29.375000  68.250000    4.162500   1004.000000
2014-09-14  29.125000  65.500000    6.712500   1004.250000
2014-09-15  29.625000  63.125000    6.712500   1004.250000
2014-09-16  30.625000  65.125000    6.250000   1002.250000
2014-09-17  30.625000  61.875000    7.400000   1002.125000
2014-09-18  30.500000  62.375000    6.712500   1003.875000
2014-09-19  31.000000  56.625000    4.175000   1003.500000
2014-09-20  31.125000  55.750000    4.400000   1002.875000
2014-09-21  30.500000  54.875000    5.562500   1003.625000
2014-09-22  30.625000  50.000000   13.437500   1004.500000
2014-09-23  31.000000  47.000000   30.685714   1004.285714
2014-09-24  29.625000  53.000000    8.100000   1006.250000
2014-09-25  30.000000  52.500000    9.725000   1007.750000

# 6. Calculate month-wise average windspeed

In [30]:
climates["wind_speed"].resample("ME").mean()

date
2013-01-31     4.833913
2013-02-28     7.474090
2013-03-31     8.757270
2013-04-30     8.046385
2013-05-31     8.943452
2013-06-30     9.593929
2013-07-31     7.358698
2013-08-31     7.384347
2013-09-30     7.593425
2013-10-31     2.836110
2013-11-30     4.252242
2013-12-31     4.986002
2014-01-31     5.560580
2014-02-28     6.402232
2014-03-31     7.123963
2014-04-30     8.868631
2014-05-31     8.576555
2014-06-30    10.111250
2014-07-31     7.528590
2014-08-31     7.665360
2014-09-30     8.054940
2014-10-31     3.988191
2014-11-30     3.126667
2014-12-31     4.133756
2015-01-31     5.261290
2015-02-28     6.317985
2015-03-31     7.701210
2015-04-30     8.530000
2015-05-31     9.065495
2015-06-30     8.769167
2015-07-31     8.580703
2015-08-31     5.477031
2015-09-30     7.229048
2015-10-31     4.930012
2015-11-30     2.117500
2015-12-31     3.795392
2016-01-31     4.285177
2016-02-29     5.950592
2016-03-31     7.204904
2016-04-30     9.687357
2016-05-31     9.506423
2016-06-30     9.052079
2016-07-31     6.207018
2016-08-31     7.168392
2016-09-30     7.508029
2016-10-31     7.291021
2016-11-30     5.993723
2016-12-31     6.132705
2017-01-31     0.000000
Freq: ME, Name: wind_speed, dtype: float64

# 7. Calculate month-wise highest meantemp

In [31]:
climates["meantemp"].resample("ME").max()

date
2013-01-31    16.500000
2013-02-28    20.800000
2013-03-31    29.166667
2013-04-30    32.125000
2013-05-31    38.714286
2013-06-30    37.166667
2013-07-31    33.857143
2013-08-31    32.500000
2013-09-30    32.750000
2013-10-31    30.833333
2013-11-30    23.428571
2013-12-31    18.000000
2014-01-31    16.625000
2014-02-28    19.625000
2014-03-31    26.250000
2014-04-30    33.250000
2014-05-31    35.250000
2014-06-30    38.500000
2014-07-31    36.625000
2014-08-31    34.125000
2014-09-30    31.250000
2014-10-31    31.000000
2014-11-30    24.125000
2014-12-31    25.000000
2015-01-31    15.125000
2015-02-28    23.125000
2015-03-31    28.500000
2015-04-30    32.875000
2015-05-31    37.750000
2015-06-30    37.625000
2015-07-31    35.714286
2015-08-31    32.625000
2015-09-30    33.000000
2015-10-31    30.000000
2015-11-30    24.000000
2015-12-31    19.250000
2016-01-31    20.142857
2016-02-29    23.875000
2016-03-31    30.000000
2016-04-30    35.687500
2016-05-31    38.272727
2016-06-30    38.200000
2016-07-31    34.187500
2016-08-31    33.809524
2016-09-30    33.444444
2016-10-31    33.269231
2016-11-30    25.640000
2016-12-31    21.208333
2017-01-31    10.000000
Freq: ME, Name: meantemp, dtype: float64

# 8. Year-wise maximum, minimum and average humidity

In [33]:
climates["humidity"].resample("YE").agg(["max", "min", "mean"])

                   max         min        mean
date
2013-12-31   94.000000   15.857143   63.046292
2014-12-31   96.857143   20.875000   59.767942
2015-12-31   98.000000   13.428571   61.430490
2016-12-31   94.300000   18.466667   58.740174
2017-12-31  100.000000  100.000000  100.000000

# 9. A new column contains previous 10 days average meantemp

In [36]:
climates["meantemp"].rolling(10).mean()

date
2013-01-01          NaN
2013-01-02          NaN
2013-01-03          NaN
2013-01-04          NaN
2013-01-05          NaN
                ...
2016-12-28    17.107129
2016-12-29    16.845224
2016-12-30    16.274748
2016-12-31    15.975011
2017-01-01    15.246440
Name: meantemp, Length: 1462, dtype: float64